### ISSUE TITLE
TODO: fix undefined behaviour (BPTR(&work) is NULL)

### ISSUE THREAD

**Issue by 0x64616E69656C** [0x64616E69656C/tinyvpn#2]
``` 
buffer.h:544:15: runtime error: null pointer passed as argument 2, which is declared to never be null
/usr/include/string.h:43:28: note: nonnull attribute specified here
    #0 0x5381a3 in buf_write_prepend /home/daniel/code/git/tinyvpn/src/./buffer.h:544:3
    #1 0x50f9e6 in openvpn_encrypt_v1 /home/daniel/code/git/tinyvpn/src/crypto.c:292:4
    #2 0x50dfd1 in openvpn_encrypt /home/daniel/code/git/tinyvpn/src/crypto.c:334:2
    #3 0x97223e in write_control_auth /home/daniel/code/git/tinyvpn/src/ssl.c:1156:7
    #4 0x9518aa in tls_process /home/daniel/code/git/tinyvpn/src/ssl.c:2259:8
    #5 0x94687b in tls_multi_process /home/daniel/code/git/tinyvpn/src/ssl.c:2542:8
    #6 0x568069 in check_tls_dowork /home/daniel/code/git/tinyvpn/src/forward.c:92:30
    #7 0x5a92cb in check_tls /home/daniel/code/git/tinyvpn/src/./forward-inline.h:40:5
    #8 0x5a83d0 in pre_select /home/daniel/code/git/tinyvpn/src/forward.c:1197:3
    #9 0x763b31 in tunnel_point_to_point /home/daniel/code/git/tinyvpn/src/openvpn.c:71:9
    #10 0x762a0e in openvpn_main /home/daniel/code/git/tinyvpn/src/openvpn.c:220:25
    #11 0x7624e1 in main /home/daniel/code/git/tinyvpn/src/openvpn.c:264:12
    #12 0x7fe386b4160f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2060f)
    #13 0x41fa18 in _start (/home/daniel/code/git/tinyvpn/src/tinyvpn+0x41fa18)
```

**Comment by 0x64616E69656C** [comment]
reported upstream 2016-03-31
